baseURL = 'https://prosseek.github.io'
languageCode = 'en-us'
title = 'John Doe - Software Developer'
theme = 'ananke'

[params]
  author = "John Doe"
  description = "Full-stack developer specializing in Laravel and modern web technologies"
  github = "https://github.com/prosseek"
  linkedin = "https://linkedin.com/in/yourusername"
  email = "john@example.com"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects" 
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
    
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false

[imaging]
  quality = 85
  resampleFilter = "lanczos"